### PR TITLE
Corrected git command in readme

### PR DESCRIPTION
**Pull request by hubbertj**
I think the git module command is incorrect or maybe it just a mac vs windows thing. But here is the PR if you want to merge it in.

### CODE REVIEW

**Comment by hubbertj** [comment]
let me know if this make sense or if I am wrong.

**Review by jafristr — APPROVED** [review]
Haha. Right after I say it's habit for me I get it wrong. Thanks! You are my first pull request who isn't me.

**Review by jafristr — APPROVED** [review]

**Comment by hubbertj** [comment]
np, good job on the project btw.

**Review by JamieFristrom — APPROVED** [review]
I see, I was the wrong me when I approved it

**Pull request merged**
